[project]
name = "ai"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "bs4>=0.0.2",
    "chromadb>=1.0.15",
    "langchain-community>=0.3.27",
    "ollama>=0.5.1",
    "pypdf>=5.9.0",
]
