# To use in Google Colab
vector_db:
  input_dir: "/content/testdata1/input_dir/"
  output_dir: "/content/testdata1/output_dir/"
  urls_path: "/content/testdata1/urls.txt"
  chroma_db_dir: "/content/ai/data/example_db/"
  chroma_db_name: 'testchroma'
  model: "nomic-embed-text"

# Ollama Model Configuration
LLM:
  model: "phi4"
