# Vector Database Configuration
vector_db:
  input_dir: "/path/to/your/data/example_data/"
  output_dir: "/path/to/your/debug_folder/"
  urls_path: "/path/to/your/data/urls.txt"
  chroma_db_dir: "/path/to/your/src/example_db/"
  chroma_db_name: 'test'
  model: "mxbai-embed-large"

  # Ollama Model Configuration
  ollama_model:
    model_name: "llama3"