# Vector Database Configuration
vector_db:
  input_dir: "/home/tagore/repos/ai/data/example_data/"
  output_dir: "/home/tagore/repos/ai/data/exampe_debug_folder"
  urls_path: "/home/tagore/repos/ai/data/example_data/urls.txt" #Be careful that this has to be a txt file.
  chroma_db_dir: "/home/tagore/repos/ai/src/example_db"
  chroma_db_name: 'test'
  model: "mxbai-embed-large"

# Ollama Model Configuration
ollama_model:
  model_name: "llama3"